# Generated by Django 4.2.7 on 2024-11-11 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('purpose', models.CharField(choices=[('idea generation', 'Idea Generation'), ('team forming, development', 'Team Forming, Development'), ('task structuring, prioritization', 'Task Structuring, Prioritization'), ('conflict resolution', 'Conflict Resolution'), ('continuous improvement, retrospectives', 'Continuous Improvement, Retrospectives'), ('alignment of vision and goals', 'Alignment of Vision and Goals'), ('facilitating effective planning', 'Facilitating Effective Planning')], max_length=255)),
                ('summary', models.CharField(default='No summary provided', help_text='This text is shown on the dashboard as short explanation of the methodology', max_length=255)),
                ('instructions', models.TextField()),
                ('material', models.TextField()),
                ('prep_time', models.CharField(choices=[('up to 5mins', 'up to 5mins'), ('up to 10mins', 'up to 10mins'), ('up to 20mins', 'up to 20mins'), ('more than 20mins', 'more than 20mins')], help_text='Enter preparation time', max_length=100)),
                ('duration', models.CharField(choices=[('up to 10mins', 'up to 10mins'), ('up to 20mins', 'up to 20mins'), ('up to 30mins', 'up to 30mins'), ('up to 60mins', 'up to 60mins'), ('more than 60mins', 'more than 60mins')], help_text='Enter duration of the excercise', max_length=100)),
                ('alt_atr', models.CharField(max_length=255, null=True)),
                ('group_size_min', models.IntegerField(default=1)),
                ('group_size_max', models.IntegerField(default=1)),
                ('location', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor/outdoor', 'Indoor/Outdoor')], default='indoor', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods_library_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='view_methods.method')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
