# Generated by Django 4.2.16 on 2024-11-02 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('purpose', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('material', models.TextField()),
                ('alt_atr', models.CharField(max_length=255)),
                ('prep_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('group_size', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods_library_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
