# Generated by Django 4.2.16 on 2024-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='group_size',
        ),
        migrations.AddField(
            model_name='method',
            name='group_size_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='method',
            name='group_size_min',
            field=models.IntegerField(default=1),
        ),
    ]
