# Generated by Django 4.2.7 on 2024-11-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0002_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
