# Generated by Django 4.2.16 on 2024-11-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0002_remove_method_group_size_method_group_size_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='alt_atr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='location',
            field=models.CharField(choices=[(0, 'Indoor'), (1, 'Outdoor'), (2, 'Indoor/Outdoor')], default='0', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='prep_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='method',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
