# Generated by Django 4.2.7 on 2024-11-20 22:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(help_text='Write the whole content of the About page. Only the first about entry in the admin panel list  is displayed on the website.'),
        ),
        migrations.AlterField(
            model_name='like',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='view_methods.method'),
        ),
    ]
