# Generated by Django 4.2.16 on 2024-11-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0004_alter_method_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='duration',
            field=models.DurationField(help_text='Enter excercise duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='prep_time',
            field=models.DurationField(help_text='Enter preparation time in minutes', null=True),
        ),
    ]
