# Generated by Django 4.2.7 on 2024-11-21 08:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0004_method_featured_image_alter_about_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='method',
            name='group_size_max',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='method',
            name='group_size_min',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='method',
            name='instructions',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='method',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor/outdoor', 'Indoor/Outdoor')], default='indoor'),
        ),
        migrations.AlterField(
            model_name='method',
            name='material',
            field=models.TextField(max_length=255),
        ),
    ]
