# Generated by Django 4.2.7 on 2024-11-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0005_alter_method_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='method',
            name='alt_atr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
