# Generated by Django 4.2.7 on 2024-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0006_alter_comment_body_alter_method_alt_atr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(help_text='Only the first about entry in the admin panel is displayed on the website.'),
        ),
        migrations.AlterField(
            model_name='method',
            name='alt_atr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='instructions',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='method',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='summary',
            field=models.CharField(default='No summary provided', help_text='This text is shown on the landing page as short explanation of the methodology', max_length=255),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
