# Generated by Django 4.2.7 on 2024-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='method',
            name='slug',
        ),
        migrations.AddField(
            model_name='method',
            name='summary',
            field=models.CharField(default='placeholder for a summary', help_text='This text is shown on the dashboard as short explanation of the methodology', max_length=255),
            preserve_default=False,
        ),
    ]
