# Generated by Django 4.2.7 on 2024-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0007_alter_about_body_alter_method_alt_atr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='summary',
            field=models.CharField(default='No summary provided', help_text='This text is shown on the landing page as short explanation of the methodology', max_length=300),
        ),
    ]
