# Generated by Django 4.2.7 on 2024-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0007_alter_comment_options_alter_method_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
            preserve_default=False,
        ),
    ]
