# Generated by Django 4.2.7 on 2024-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0008_alter_method_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToTeamcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
