# Generated by Django 4.2.7 on 2024-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0009_messagetoteamcraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetoteamcraft',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='messagetoteamcraft',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='messagetoteamcraft',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
