# Generated by Django 4.2.7 on 2024-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0010_remove_method_duration_remove_method_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='duration',
            field=models.CharField(choices=[('up to 10mins', 'up to 10mins'), ('up to 20mins', 'up to 20mins'), ('up to 30mins', 'up to 30mins'), ('up to 60mins', 'up to 60mins'), ('more than 60mins', 'more than 60mins')], default='up to 10mins', help_text='Enter duration of the excercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='prep_time',
            field=models.CharField(choices=[('up to 5mins', 'up to 5mins'), ('up to 10mins', 'up to 10mins'), ('up to 20mins', 'up to 20mins'), ('more than 20mins', 'more than 20mins')], default='up to 5mins', help_text='Enter preparation time'),
            preserve_default=False,
        ),
    ]
