# Generated by Django 4.2.7 on 2024-11-24 09:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0010_alter_messagetoteamcraft_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageToTeamcraft',
        ),
        migrations.AlterField(
            model_name='method',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', help_text='Recommended image size: 700x280px.Maximum file size: 3MB.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='method',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor/outdoor', 'Indoor/Outdoor'), ('remote', 'Remote')], default='indoor'),
        ),
    ]
