# Generated by Django 4.2.7 on 2024-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0011_delete_messagetoteamcraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='method',
            name='location',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('indoor/outdoor', 'Indoor/Outdoor')], default='indoor'),
        ),
    ]
