# Generated by Django 4.2.7 on 2024-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0011_method_duration_method_prep_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='purpose',
            field=models.CharField(choices=[('idea generation', 'Idea Generation'), ('team forming, development', 'Team Forming, Development'), ('task structuring, prioritization', 'Task Structuring, Prioritization'), ('conflict resolution', 'Conflict Resolution'), ('continuous improvement, retrospectives', 'Continuous Improvement, Retrospectives'), ('alignment of vision and goals', 'Alignment of Vision and Goals'), ('facilitating effective planning', 'Facilitating Effective Planning')]),
        ),
    ]
