# Generated by Django 4.2.7 on 2024-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_methods', '0012_method_remote_alter_method_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='remote',
            field=models.BooleanField(default=False, help_text='Check if the method can be alsoused for a remote session'),
        ),
    ]
